### ISSUE TITLE
Close icon not resized

### ISSUE THREAD

**Issue by mikemaer1990** [sricharankrishnan/click-image-play-youtube-video#16]
Everything about this is amazing. Thanks for making it.

The only issue I had once it was set up was the X icon to close was huge. I have bootstrap set up so it should have been resized but it wasn't.

I set width of the close icon:

`/* .closeIcon img {
  width: 100%;
  height: auto;
} */`

And display flex to the .videoPlayerOverlay .closeIcon.

That fixed it for me.

![x](https://user-images.githubusercontent.com/30853323/118238541-383fd400-b4cb-11eb-84d2-38b39fcdea8b.png)

**Comment by sricharankrishnan** [comment]
Hey Mike.
Thank you writing in and Im super grateful that you like the plugin and its helping you with your build. I've made the necessary changes to the plugin files.
Do check and let me know if its ok with the changes I've made, message me back. Will have this issue closed up then.

Cheers and good day!

**Comment by mikemaer1990** [comment]
Working great 👍

Have a good one!
