### ISSUE TITLE
Stop & Close Video When Clicking Outside Iframe

### ISSUE THREAD

**Issue by mikemaer1990** [sricharankrishnan/click-image-play-youtube-video#18]
Not an issue, but I am trying to make it so the video will close and stop playing when the user clicks outside of the iframe.

Like it is [Here](https://www.rottentomatoes.com/tv/mare_of_easttown/s01)

I have zero experience with jQuery, and I don't know if you even want this to be a feature.

I currently am just using javascript to detect mouse clicks not on the video element and then I am calling closeVideoOverlay(), but the video is still playing and I can't figure out how to do so.

**Comment by sricharankrishnan** [comment]
Hey Mike,
Good to hear from you again. Yes I will have this feature added to the plugin and send you a message. BTW, I believe if you press the escape key from your desktop/laptop, that would also help close the video frame. Do try to see if that works.

Will send you a message once this issue is sorted out!

Cheers

**Comment by sricharankrishnan** [comment]
Hey,

I've just made the necessary updates and believe this should be ok. It would be great if you could test it out and see if things are in order. Here are the things I've done

- I've added the code for the feature request in the plugin js file. You would be able to get that js file from the ```plugin-bundle-files```  directory
- I have created a branch called ```feature```, you could perform a git fetch if you would like or just switch to the branch and manually perform download/clone from github directly
- done some testing on FF and Chrome in responsive mode and seems ok. I've also got a slightly large Samsung phone on which I am able to see the transparent overlay. On clicking that its closing.

So yeah let me know if this is what you had expected. Waiting for your response

**Comment by mikemaer1990** [comment]
Very nice! Just updated my js file with your features update. Working perfectly 👌.

Yeah, I knew that escape works but I thought it made sense to also have it close when clicking off the video.

Thanks for your responses and for taking my feedback in! Again, I really appreciate what you've made here and will use it in any future projects that require it and have you as the source.

If I come up with any other ideas, I'll let you know! Hope you don't mind, haha it seems like you are a professional.

**Comment by sricharankrishnan** [comment]
You are welcome to give me ideas if something comes up. I'm not some great coder but I do try my best in this space. Let me know if something comes up and I'll do my best to support.

God Bless. Stay safe from COVID19 and Be Well! Code well.
Good wishes to your family too
